### ISSUE TITLE
Error extracting armatures

### ISSUE THREAD

**Issue by aldergames** [chinedufn/landon#8]
I'm trying to use landon to extract armatures from .blend files. I'm using the code from https://www.chinedufn.com/3d-webgl-basic-water-tutorial/ as a base, and have modified it to use `std::path::PathBuf` which is used in the latest version of landon.

I've installed landon and run the `landon blender install armature-to-json`. This is from my Cargo.lock:
```
[[package]]
name = "landon"
version = "0.6.0"

[[package]]
name = "blender-armature"
version = "0.2.6"
```

This is the minimal `build.rs` that causes this issue (using the bird.blend from https://github.com/chinedufn/webgl-water-tutorial):
```
use landon;
use std::path::PathBuf;

fn main() {
    let blender_files: std::vec::Vec<PathBuf> = vec![
		PathBuf::from("./assets/meshes/bird.blend"),
	];
    let blender_stdout = landon::export_blender_data(&blender_files).unwrap();
}
```
This produces the output when running `cargo build`:
```
error: failed to run custom build command for `project v0.1.0 (D:\dev\rust\project)`

Caused by:
  process didn't exit successfully: `D:\dev\rust\project\target\debug\build\project-8b00cef0c70f0e01\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Traceback (most recent call last):\r\n  File \"<string>\", line 15, in <module>\r\n  File \"C:\\Program Files\\Blender Foundation\\Blender\\2.80\\scripts\\modules\\bpy\\ops.py\", line 201, in __call__\r\n    ret = op_call(self.idname_py(), None, kw)\r\nAttributeError: Calling operator \"bpy.ops.rigging.iktofk\" error, could not be found\r\n\r\nlocation: <unknown location>:-1\r\n\r\nlocation: <unknown location>:-1\r\n"', build.rs:50:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There seems to be something wrong with the `bpy.ops.rigging.iktofk` function missing. Is this in landon and its scripts, or something missing in blender? I'm using an unmodified blender 2.80.

Something to note: the code works if I only import terrain.blend (which doesn't have armatures).

**Comment by chinedufn** [comment]
Ah so you need to run this:

```
# https://github.com/chinedufn/blender-iks-to-fks#install-via-script
npm install -g blender-iks-to-fks && ik2fk --install
```

I have it in mind to eventually move `blender-iks-to-fks` into Landon so apologies for the inconvenience of it being in another place.

But that should work - let me know if you have any other issues!

**Comment by aldergames** [comment]
This worked, thanks!

One question though: I skimmed through the readme of the blender-iks-to-fks repo and your post on IKs on reddit. As I understand it, landon performs the ik2fk operation by default when parsing blender files, and the operation removes all IK from the model.

What if one wanted to use the IK (including joint constraints) defined in blender to perform IK solving in-engine? Say if you wanted to have a game with a character moving around, and have dynamic foot placement based on terrain geometry. Does the current flow of landon support something like that?

**Comment by chinedufn** [comment]
Great!

None of that is currently supposed by Landon - for no other reason than I haven’t needed it yet so I haven’t thought much about it.

It’s in the way back of my mind to someday do some experimentation with building an IK demo as a learning exercise - but at this very moment it’s not on my radar.

Hope that helps!

**Comment by chinedufn** [comment]
@aldergames were you able to get your data out of Blender? 

Anything that you think could have been better documented?

Cheers!

**Comment by aldergames** [comment]
Sorry for late answer; my focus hasn't been on animations lately. I did verify this now: I can get an animated mesh in rust/webgl.

Since I was using the https://www.chinedufn.com/3d-webgl-basic-water-tutorial/ as a base, I had to refactor the code a little bit (it uses an older version of Landon where the attributes have different names). So if anything is needed documentation wise, probably a good up-to-date example on how to use the library. This might exist somewhere already, but I solved it by digging around in the source of Landon to figure out what the new functions to use were.

The entire concept of Multi/Single Indexed attributes is a bit of a handful to get around. Which kind of applications would use Multi Indexed? Is this how Blender usually saves the data or? For realtime 3d with WebGL (or similar) I think there's no reason to try to do anything other than Single Indexed?

**Comment by chinedufn** [comment]
@aldergames thanks!

Yeah Blender has the data multi-indexed, but when working with real time graphics APIs you wouldn't use multi indexed. It's only useful for saving storage space.

Yeah the Landon crate has a `mesh-visualizer` example project but it's also old and out of date and generally bad Rust since I wrote it when I was learning Rust.

I'm looking to update that later in the year.

Yeah I'm actually looking to completely revamp the multi/single indexed thing and instead just have a `Vec<Vertex>`.

The concept of multi vs. single would disappear and instead you would just have vertices that pointed to another vector for their data (so multiple vertices could point to the same externally stored normal .. this handles the multi indexed case basically) Or have their data inlined (the single indexed case)

So instead of multi indexed it'd look something like this

```
struct Vertex {
  // 50th normal
  normal: SomeEnum::Indexed(50),
  // 25th uv
  uv: SomeEnum::Indexed(25)
}

let normals: Vec<[f32; 3]> = lots_of_normals();
let uvs: Vec<[f32; 2]> = lots_of_uvs();
```

And what is now single indexed would instead just be 

```
struct Vertex {
  // 50th normal
  normal: SomeEnum::Inline([0.; 3]),
  // 25th uv
  uv: SomeEnum::Inline([1.; 2])
}
```

This is just a rough sketch and I haven't thought about it deeply yet. I could look different. But tl;dr that confusing structure of multi vs. single will go away.

Cheers!

**Comment by aldergames** [comment]
I'm using this code (and a few other repos I've found) to try to learn rust+wasm+webgl and do some experiments for my own projects. So far it's been really helpful! I did see the mesh-vizualizer, but that one doesn't have code for skinned meshes (as far as I could tell).

**Comment by chinedufn** [comment]
Nice I'm glad you're making progress!

I've started working on moving towards a better data model for the vertices

https://github.com/chinedufn/landon/pull/13

Yeah the mesh-visualizer is on my backburner to re-write and it'll have skinning / PBR / etc and be deployed via GH pages. 

Just don't know when I'll make time for it, so check back in a few months fingers crossed!

**Comment by aldergames** [comment]
Nice! I'll be keeping an eye out. If I can make feature requests, I know that I'll need IK in some form in the future (not necessarily full code for actually using the IK, but I do need to import IK rigs from blend files). Keep trucking at your projects, it's already been a ton of help.

**Comment by chinedufn** [comment]
Thanks!

I’d be happy to expose more IK info. Just lmk when you get closer to needing it and knowing exactly what you need and we can figure out how to get the right data out of Blender for your needs

Cheers!
